mobile_homepage:
    path:     /
    defaults: { _controller: MobileBundle:Default:index }

findall:
    path:     /evenement/afficher
    defaults: { _controller: MobileBundle:Evenement:findall }

findbyid:
    path:     /evenement/afficher/{id}
    defaults: { _controller: MobileBundle:Evenement:findbyid }

findbynom:
    path:     /evenement/affichernom/{nom}
    defaults: { _controller: MobileBundle:Evenement:findbynom }


new:
    path:     /evenement/new/{idmembre}/{nom}/{lieu}/{description}/{nbrmaxparticipant}/{image}
    defaults: { _controller: MobileBundle:Evenement:new }


findallparticipation:
    path:     /participation/All
    defaults: { _controller: MobileBundle:Participation:findall }

newparticipation:
    path:     /participation/new/{idevenement}/{iduser}
    defaults: { _controller: MobileBundle:Participation:participer }

supprimerparticipation:
    path:     /participation/supprimer/{idevenement}/{iduser}
    defaults: { _controller: MobileBundle:Participation:abondonner }



findallaimerevenement:
    path:     /aimer/All
    defaults: { _controller: MobileBundle:AimerEvenement:findall }

newaimerevenement:
    path:     /aimer/new/{idevenement}/{iduser}
    defaults: { _controller: MobileBundle:AimerEvenement:aimer }

supprimeraimerevenement:
    path:     /aimer/supprimer/{idevenement}/{iduser}
    defaults: { _controller: MobileBundle:AimerEvenement:aimerpas }


findalluser:
    path:     /user/All
    defaults: { _controller: MobileBundle:User:findall }

registeruser:
    path:     /user/register/{username}/{email}/{password}/{sexe}/{telephone}/{image}/{ville}
    defaults: { _controller: MobileBundle:User:register }

loginusert:
    path:     /user/login/{email}/{password}
    defaults: { _controller: MobileBundle:User:login }